version: "2"
services:
  # deconz:
  #   image: marthoc/deconz
  #   container_name: deconz
  #   network_mode: host
  #   restart: always
  #   volumes:
  #     - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
  #   devices:
  #     - /dev/ttyAMA0
  #   environment:
  #     - DECONZ_WEB_PORT=8585
  #     - DECONZ_WS_PORT=444
  #     - DECONZ_VNC_MODE=1
  #     - DECONZ_VNC_PORT=5900
  #     - DEBUG_INFO=1
  #     - DEBUG_APS=0
  #     - DEBUG_ZCL=0
  #     - DEBUG_ZDP=0
  #     - DEBUG_OTAU=0

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Amsterdam

  ######################################
# Zigbee2MqttAssistant (GUI Interface)
######################################
# https://github.com/yllibed/Zigbee2MqttAssistant

  zigbee2mqttAssistant:
    image: carldebilly/zigbee2mqttassistant
    container_name: zigbee2mqttAssistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER={localhost}
      - Z2MA_SETTINGS__MQTTUSERNAME={}
      - Z2MA_SETTINGS__MQTTPASSWORD={}
      # Set to your TimeZone when using on Linux https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Won't work if you're using the Windows version of the container
      - TZ=Europe/Copenhagen
    ports:
      - 8880:80
    restart: unless-stopped
